// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArcBicJizuqRGoq9VL4pvtuTuvO9BREV0',
    appId: '1:629062106224:web:56d242974b89da223208b5',
    messagingSenderId: '629062106224',
    projectId: 'consx-user-app',
    authDomain: 'consx-user-app.firebaseapp.com',
    storageBucket: 'consx-user-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh_yxu-Dih2J9sNLF7R9HrPSsvgjRACGw',
    appId: '1:629062106224:android:daad39ab134787703208b5',
    messagingSenderId: '629062106224',
    projectId: 'consx-user-app',
    storageBucket: 'consx-user-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0qQE-j1ffoDf9TwaYwW90t0N3_N6m8zs',
    appId: '1:629062106224:ios:7f05a61f10de1d6a3208b5',
    messagingSenderId: '629062106224',
    projectId: 'consx-user-app',
    storageBucket: 'consx-user-app.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0qQE-j1ffoDf9TwaYwW90t0N3_N6m8zs',
    appId: '1:629062106224:ios:7f05a61f10de1d6a3208b5',
    messagingSenderId: '629062106224',
    projectId: 'consx-user-app',
    storageBucket: 'consx-user-app.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArcBicJizuqRGoq9VL4pvtuTuvO9BREV0',
    appId: '1:629062106224:web:041e05205818ff643208b5',
    messagingSenderId: '629062106224',
    projectId: 'consx-user-app',
    authDomain: 'consx-user-app.firebaseapp.com',
    storageBucket: 'consx-user-app.appspot.com',

  );
}
